Visual Studio Folder/QRSCS_MS/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace QRSCS_MS.Models
{
    public class LoginModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }

    }
}

Visual Studio Folder/QRSCS_MS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QRSCS_MS.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

Visual Studio Folder/QRSCS_MS/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QRSCS_MS.Controllers
{
    public class EditorController : Controller
    {
        // GET: Editor
        public ActionResult IEP()
        {
            return View();
        }
    }
}

Visual Studio Folder/QRSCS_MS/Controllers/IDDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QRSCS_MS.Controllers
{
    public class IDDController : Controller
    {
        // GET: IDD
        public ActionResult OT()
        {
            return View();
        }
    }
}

Visual Studio Folder/QRSCS_MS/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QRSCS_MS.Models;

namespace QRSCS_MS.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel lgm)
        {
            if(ModelState.IsValid)
            {
                return RedirectToAction("Dashboard", "Dashboard");
            }
            else
            {
                return View();
            }
            

            
        }
    }
}

Visual Studio Folder/QRSCS_MS/Views/Dashboard/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>Cards Samples</title>
    <link rel="stylesheet" href="~/Content/css/cards.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <div class="container card-container">

        <!-- -------------- Welcome Heading Row -------------- -->
        <div class="row">
            <div class="col-sm welcome-heading-col">
                <h1 class="welcome-heading">Welcome to QRSCS Dashboard</h1>
            </div>
        </div>

        <!-- -------------- Cards Row # 01 -------------- -->
        <div class="row">
            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>

            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>

            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>

            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>
        </div>

        <!-- -------------- Cards Row # 02 -------------- -->
        <div class="row mt-5">
            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>

            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>

            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>

            <div class="col-sm card-col">
                <div class="row card-content">
                    <span class="card-content__count">150</span>
                    <br>
                    <p class="card-content__text">New orders</p>
                </div>
                <div class="row card-link">
                    <p class="card-link__text">More info</p>
                </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

Visual Studio Folder/QRSCS_MS/Views/Login/Login.cshtml
@model QRSCS_MS.Models.LoginModel
@{ 
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--------------------------- META INFORMATION ------------------------------>

    <title>QRSCS Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!------------------------- LINKING STYLE SHEETS ---------------------------->
    <!-- Login Main Style Sheet -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/Login.css">
    <!-- Utiilities Style Sheet -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/utilities.css">
    <!-- Google Font Roboto Style Sheet -->
    <link rel="stylesheet" href="~/Content/css/font-roboto.css">
    <!-- Bootstrap Style Sheet -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">
    <!-- Icons Style Sheet -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/iconic-font.min.css">

    <!---------------------------- LINKING FAVICON ------------------------------->

    <link rel="icon" type="image/png" href="~/Content/assets/images/logo.png" />

</head>

<body>

    <!--Overall Login Screen-->
    <div class="login-screen">
        <!--Login Form Container-->
        <div class="login-form-container">
            <!--Form Wrapper-->
            <div class="login-form-wrap">

                @*@using (Html.BeginForm(FormMethod.Post)) {*@

                <!--Login Form-->
                <form class="login-form validate-form" action="#" method="POST">

                    <!--Form Logo -->
                    <span class="login-form__logo"><img src="~/Content/assets/images/logo.png"></span>

                    <!--Form Heading-->
                    <span class="login-form__title p-b-34 p-t-27"> Login </span>

                    <!--Form Inputs: Username-->
                    <div class="login-form__input-container validate-input" data-validate="Username Missing">
                        @*<input class="login-form__input" type="text" name="login-username" placeholder="Username">*@
                        @Html.TextBoxFor(x => x.Username, null, new { @class = "login-form__input", type = "text", name = "login-username", placeholder = "Username" })
                        <span class="login-form__input-focus" data-placeholder="&#xf207;"></span>
                    </div>

                    <!--Form Inputs: Password-->
                    <div class="login-form__input-container validate-input" data-validate="Password Missing">
                        @*<input class="login-form__input" type="password" name="login-password" placeholder="Password">*@
                        @Html.TextBoxFor(x => x.Password, null, new { @class = "login-form__input", type = "password", name = "login-password", placeholder = "Password" })
                        <span class="login-form__input-focus" data-placeholder="&#xf191;"></span>
                    </div>

                    <!--Remember Me Checkbox-->
                    <div class="login-form__checkbox-container">
                        <input class="login-form__checkbox-input" id="remember-me-chk" type="checkbox" name="login-remember-me">
                        <label class="login-form__checkbox-label" for="remember-me-chk">Remember me</label>
                        <a class="login-form__forget" href="#">Forgot Password?</a>
                    </div>

                    <!--Login Button-->
                    <div class="login-form__btn-container">
                        <button class="login-form__btn"><a @*href=<"@Url.Action("Dashboard", "Dashboard")"*@>Login</a></button>
                    </div>
                    @*  *@}
                </form>

            </div>
        </div>
    </div>

    <!---------------------------- LINKING SCRIPTS ------------------------------->

    <!--Login Script-->     <script src="~/Content/js/Login.js"></script>
    <!--Bootstrap Script--> <script src="~/Content/js/bootstrap.min.js"></script>
    <!--JQuery Script-->    <script src="~/Content/js/jquery.js"></script>

</body>

</html>

Visual Studio Folder/QRSCS_MS/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <!--------------------------- META INFORMATION ------------------------------>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!------------------------- LINKING STYLE SHEETS ---------------------------->
    <!-- Dashboard Style Sheet -->
    <link rel="stylesheet" href="~/Content/css/Dashboard.css">
    <!-- Google Fonts Style Sheet -->
    <link rel="stylesheet" href="~/Content/css/font-roboto.css">

</head>

<body>
    <div class="main-container">
        <!---------------------- Building Header ----------------------->
        <header class="header">

            <!-- Header Hamburger Icon -->
            <div class="header-hamburger">
                <input type="checkbox" id="header-hamburger__checkbox" onchange="openCloseSidebar()">
                <label for="header-hamburger__checkbox" class="header-hamburger__label">
                    <div></div>
                    <div></div>
                    <div></div>
                </label>
            </div>

            <!-- Header Logo -->
            <div class="header-logo">
                <img src="~/Content/assets/images/logo.png" alt="Logo Image" class="header-logo__img">
                <noscript><img src="images/multiwebpress.png" alt="Logo Image" class="header-logo__img"></noscript>
            </div>

            <!-- Header User Profile & Signout -->
            <div class="header-user">
                <img src="~/Content/assets/images/dashboard__user.png" alt="User Image" class="header-user__img">
                <a href="#"><h2 class="header-user__name">Munzah Shah</h2></a>
                <a href="#"><img src="~/Content/assets/images/dashboard__signout.png" alt="Logo Image" class="header-user__signout"></a>
            </div>
        </header>

        <!-- Building Middle Section (Main Dashboard) -->
        <div class="middle-window">

            <!---------------------- Building The Fixed SideBar ---------------------->
                <div class="middle-window__Sidebar">
                    <aside class="sidebar" id="sidebar">
                        <ul>

                            <!-- Home Link -->
                            <li class="sidebar-menu__box">
                                <a class="sidebar-menu__item" href="@Url.Action("Dashboard", "Dashboard")">
                                    <img src="~/Content/assets/images/dashboard__home.png" alt="icon home" class="sidebar-menu__icon">
                                    <span>Home</span>
                                </a>
                            </li>

                            <!-- Create User Link -->
                            <li class="sidebar-menu__box">
                                <a class="sidebar-menu__item" href="#">
                                    <img src="~/Content/assets/images/dashboard__add-user.png" alt="icon add user" class="sidebar-menu__icon">
                                    <span>Create User</span>
                                </a>
                            </li>

                            <!-- Editor Section Link -->
                            <li class="sidebar-menu__box">
                                <img src="~/Content/assets/images/dashboard__editor-section.png" alt="icon add user" class="sidebar-menu__icon">
                                <!-- Editor Section Collapsible Sub Menus -->
                                <div class="dash__wrap-collabsible">
                                    <input id="dash__collapsible1" class="dash__collapsible dash__toggle" type="checkbox">
                                    <label for="dash__collapsible1" class="dash__lbl-toggle sidebar-menu__item">Editor Section</label>
                                    <div class="dash__collapsible-content">
                                        <div class="dash__content-inner">
                                            <ol type="1" class="sidebar-submenu">
                                                <li><a class="sidebar-submenu__subitem" href="#">Admission Form</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Case History Form</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="@Url.Action("IEP", "Editor")">Individualized E-Plan</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Add Teacher</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Withdraw Student</a></li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <!-- Hearing Impaired Link -->
                            <li class="sidebar-menu__box">
                                <img src="~/Content/assets/images/dashboard__hearing-impaired.png" alt="icon add user" class="sidebar-menu__icon">
                                <!-- Hearing Impaired Collapsible Sub Menus -->
                                <div class="dash__wrap-collabsible">
                                    <input id="dash__collapsible2" class="dash__collapsible dash__toggle" type="checkbox">
                                    <label for="dash__collapsible2" class="dash__lbl-toggle sidebar-menu__item">Hearing Impaired</label>
                                    <div class="dash__collapsible-content">
                                        <div class="dash__content-inner">
                                            <ol type="1" class="sidebar-submenu">
                                                <li><a class="sidebar-submenu__subitem" href="#">Speech Case History</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Audiology Assessment</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Speech Assessment</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Performance</a></li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <!-- Visual Impaired Link -->
                            <li class="sidebar-menu__box">
                                <img src="~/Content/assets/images/icon-visual-impaired.png" alt="icon add user" class="sidebar-menu__icon">
                                <!-- Visual Impaired Collapsible Sub Menus -->
                                <div class="dash__wrap-collabsible">
                                    <input id="dash__collapsible3" class="dash__collapsible dash__toggle" type="checkbox">
                                    <label for="dash__collapsible3" class="dash__lbl-toggle sidebar-menu__item">Visual Impaired</label>
                                    <div class="dash__collapsible-content">
                                        <div class="dash__content-inner">
                                            <ol type="1" class="sidebar-submenu">
                                                <li><a class="sidebar-submenu__subitem" href="#">Performance</a></li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <!-- IDD Link -->
                            <li class="sidebar-menu__box">
                                <img src="~/Content/assets/images/dashboard__idd.png" alt="icon add user" class="sidebar-menu__icon">
                                <!-- IDD Collapsible Sub Menus -->
                                <div class="dash__wrap-collabsible">
                                    <input id="dash__collapsible4" class="dash__collapsible dash__toggle" type="checkbox">
                                    <label for="dash__collapsible4" class="dash__lbl-toggle sidebar-menu__item">IDD</label>
                                    <div class="dash__collapsible-content">
                                        <div class="dash__content-inner">
                                            <ol type="1" class="sidebar-submenu">
                                                <li><a class="sidebar-submenu__subitem" href="#">IQ-Test</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Psychological Assessment</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="@Url.Action("OT", "IDD")">Occupational Therapy</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Child Sensory Profile</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Physio Profile</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">Behavioral Profile</a></li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <!-- Result Section Link -->
                            <li class="sidebar-menu__box">
                                <img src="~/Content/assets/images/dashboard__result-section.png" alt="icon add user" class="sidebar-menu__icon">
                                <!-- Result Section Collapsible Sub Menus -->
                                <div class="dash__wrap-collabsible">
                                    <input id="dash__collapsible5" class="dash__collapsible dash__toggle" type="checkbox">
                                    <label for="dash__collapsible5" class="dash__lbl-toggle sidebar-menu__item">Result Section</label>
                                    <div class="dash__collapsible-content">
                                        <div class="dash__content-inner">
                                            <ol type="1" class="sidebar-submenu">
                                                <li><a class="sidebar-submenu__subitem" href="#">HI-Result Card</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">VI-Result Card</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">IDD-Result Card</a></li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <!-- School View Link -->
                            <li class="sidebar-menu__box">
                                <img src="~/Content/assets/images/dashboard__school-view.png" alt="icon add user" class="sidebar-menu__icon">
                                <!-- School View Collapsible Sub Menus -->
                                <div class="dash__wrap-collabsible">
                                    <input id="dash__collapsible6" class="dash__collapsible dash__toggle" type="checkbox">
                                    <label for="dash__collapsible6" class="dash__lbl-toggle sidebar-menu__item">School View</label>
                                    <div class="dash__collapsible-content">
                                        <div class="content-inner">
                                            <ol type="1" class="sidebar-submenu">
                                                <li><a class="sidebar-submenu__subitem" href="#">All Users</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">All Teachers</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">All Students</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">All HI-Students</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">All VI-Students</a></li>
                                                <li><a class="sidebar-submenu__subitem" href="#">All IDD-Students</a></li>
                                            </ol>
                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </aside>
                </div>

            <!---------------------- Building The Center Screen (Dasboard) ---------------------->
            <div class="middle-window__dashboard">
            @RenderBody()
            </div>

        </div>


        <!---------------------- Building The Footer ---------------------->
        <footer class="footer">
            <!-- Footer Text -->
            <div class="footer-text">
                Powered by <a href="https://pluraldynamics.com/" target="_blank">Plural Dynamics</a>
            </div>
        </footer>

    </div>


    <!--Linking Scripts-->
    <script type="text/javascript" src="~/Content/js/Dashboard.js"></script>
</body>

</html>